name: Terraform EC2 Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'ec2-deployment/**'
      - '.github/workflows/ec2-deploy.yml'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./ec2-deployment
        run: terraform init -upgrade

      - name: Terraform Validate
        working-directory: ./ec2-deployment
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./ec2-deployment
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./ec2-deployment
        run: terraform apply -auto-approve tfplan
